apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: cert-manager
 namespace: cert-manager
spec:
 acme:
  email: kravcheko.leon@gmail.com
  privateKeySecretRef:
   name: db-user-pass2
  server: https://acme-staging-v02.api.letsencrypt.org/directory
  dns01:
    providers:
    - name: cloud-dns-provider
      clouddns:
        project: absolute-router-242207
        serviceAccountSecretRef:
          key: account.json
          name: db-user-pass
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: cert-manager
 namespace: istio-system
spec:
 secretName: istio-ingressgateway-certs
 acme:
   config:
    - dns01:
        provider: cloud-dns-provider
      domains:
      - "rebeldance.kiev.ua"
      - "*.rebeldance.kiev.ua"
 commonName: rebeldance.kiev.ua
 dnsNames:
 - "rebeldance.kiev.ua"
 - "*.rebeldance.kiev.ua"
 issuerRef:
   name: cert-manager
   # We can reference ClusterIssuers by changing the kind here.
   # The default value is Issuer (i.e. a locally namespaced Issuer)
   kind: ClusterIssuer
