apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: spin
    cluster: spin-gate
  name: spin-gate-lb
  namespace: spinnaker
spec:
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: spin
    cluster: spin-gate
  type: LoadBalancer
