{
 "title": "Our_app",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values({namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values({namespace=\"$namespace\" , pod_name=\"$pod\"} , container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=\"$pod\"}) *100",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Cpu_used",
   "type": "graph",
   "description": "The chart aggregates usage for all pods currently matching the service's selector: pods that have been removed (for example evicted from node) do not count towards it.",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod_name=\"$pod\"}[1m]))",
     "legendFormat": "{{ pod_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "The chart aggregates usage for all pods currently matching the service's selector: pods that have been removed (for example evicted from node) do not count towards it.",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 9 },
   "repeat": "namespace",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name)(container_memory_usage_bytes{container_name!=\"POD\",pod_name=\"$pod\"}) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}